CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS users(
    pk BIGSERIAL PRIMARY KEY,
    id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
    login VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
);
